### PR TITLE
New styles

### PR DESCRIPTION
**Pull request by mirshko**
Should be a lot easier to compare changes now, sorry about that.

### CODE REVIEW

**Comment by mirshko** [comment]
@gillesdemey What do you think about the changes?

**Comment by gillesdemey** [comment]
I'll need some time to check out the branch, liking the sass variables so far!

**Comment by mirshko** [comment]
@gillesdemey Been about a week? No 🎲 ?

**Comment by Hum4n01d** [comment]
It doesn’t work for me… I just get a window

**Comment by mirshko** [comment]
@Hum4n01d did you build it right?

**Comment by mirshko** [comment]
Oops

**Comment by Hum4n01d** [comment]
No; I ran `electron .` Shouldn’t that work?

**Comment by mirshko** [comment]
You might need to npm install first

**Comment by Hum4n01d** [comment]
Maybe the problem is that I `yarn install`ed instead…

**Comment by mirshko** [comment]
https://www.dropbox.com/s/cn1k3yd5240hkus/Screenshot%202017-02-06%2021.23.02.png?dl=0

It works fine for me when I packaged it.

**Comment by mirshko** [comment]
Yeah it uses npm, never worked with yarn before

**Comment by Hum4n01d** [comment]
Ah ok

**Comment by Hum4n01d** [comment]
Still doesn’t work though

**Comment by Hum4n01d** [comment]
I ran `npm install` and then `electron .` and got a blank Cumulus window and this in the console:

`/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.5/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 1 `

**Comment by mirshko** [comment]
thats weird. All this branch edits is the styles. @gillesdemey ?

**Comment by seppestas** [comment]
Hey @Hum4n01d, this looks like a problem related to Electron/Chromium rather than Cumulus. Can you check if you can launch other Electron apps on your system?

What version of Electron are you using?

**Comment by Hum4n01d** [comment]
@seppestas Ok, I'll check when I get a chance

**Comment by gillesdemey** [comment]
I does sounds like something rather related to Electron; FWIW I can build it on my local system and the style changes shouldn't impact anything in particular.

Merging this for now and will create a new release — thanks for the hard work (and the patience) 👍

**Comment by gillesdemey** [comment]
Released as [v0.10.0](https://github.com/gillesdemey/Cumulus/releases/tag/v0.10.0)

**Comment by Hum4n01d** [comment]
Yay!

**Comment by mirshko** [comment]
Sweeeeeet! :D thanks @gillesdemey Glad you liked the update!

**Comment by mirshko** [comment]
Let me know if there is anything else I can help with!

**Pull request merged**
