### PR TITLE
fix #110 - restore dependency in yarn

### LINKED ISSUE #110: Uncaught Exception: Error: Cannot find module 'electron-settings'
Hi,

I got an exception when starting to run the application that I compiled locally.

A JavaScript error occurred in the main process
Uncaught Exception: Error: Cannot find module 'electron-settings'
at Module._resolveFilename(module.js:470:15)
...

exception

Do you have any ideas for it?

### LINKED ISSUE #111: Should we add package-lock.json to gitignore or git tree?
npm makes package-lock.json automatically at building time.
Should we add it to git repository or ignore it?

### PR DESCRIPTION
**Pull request by star114**
https://stackoverflow.com/questions/44343997/npm-notice-created-a-lockfile-as-package-lock-json-you-should-commit-this-file

### CODE REVIEW

**Comment by MichielDeMey** [comment]
This project currently uses Yarn as the dependency manager and currently has a lockfile for dependencies.

**Comment by star114** [comment]
@MichielDeMey 
According to [README.md](https://github.com/gillesdemey/Cumulus#install-dependencies), this project also uses npm.
If it uses Yarn only, should we update README.md?

**Comment by MichielDeMey** [comment]
You're correct, we should reflect the use of Yarn in our README.
Best to create a new issue for that or squash the commits of this PR. 👍

**Comment by star114** [comment]
@MichielDeMey Thanks for your kind reply.

BTW,
As I report the issue, #110, (not #111) something is wrong with Yarn on the current master branch.
anitricks guided me to use npm instead of Yarn, and I resolved my issue and built completely.
Don't you know any related problem in your developing environment?

I'll try to build it again using Yarn, but please have a look first.

**Pull request closed without merging**
