### PR TITLE
Update README.md with new app screenshot

### PR DESCRIPTION
**Pull request by mirshko**
Adding new image for the README file. Reflects redesign as of 10.0. Also is retina-ready for high resolution screens.

### CODE REVIEW

**Comment by Hum4n01d** [comment]
Sweet, I made an issue for this already #85

**Comment by MichielDeMey** [comment]
Hi, thanks for the PR but we're going to have to change it in the github pages to reflect the new style to the project site as well.

**Comment by mirshko** [comment]
@MichielDeMey I can do that if you'd like. If not here is the screenshot used. 

https://www.dropbox.com/s/7ijw6d1m14bqi3s/Screenshot%202017-02-22%2008.59.12.png?dl=0

**Comment by gillesdemey** [comment]
@mirshko Can you add the PNG file to the project as part of this PR? Then we can simply include it with an `` tag in the README 

ie. ``

**Comment by gillesdemey** [comment]
@MichielDeMey @mirshko I've already gone ahead and updated the `gh-pages` branch though I had to redo the screenshot since the original one wasn't transparent

**Comment by mirshko** [comment]
@gillesdemey Done!

**Comment by gillesdemey** [comment]
LGTM!

**Pull request merged**
