### PR TITLE
added linux build task

### PR DESCRIPTION
**Pull request by sclausen**

### CODE REVIEW

**Comment by gillesdemey** [comment]
Thanks for this! :+1:  

We're currently looking into building and supporting the app on all three major platforms — we're currently doing some testing and research to figure out what needs to be done to properly support them.

This includes build tasks, but also testing for bugs and broken features. We'll definitely merge this when we've deemed the Linux version to be ready.

**Comment by khaledvic** [comment]
Hey
any updates?

**Comment by gillesdemey** [comment]
@khaledvic  We're currently not committed to releasing and maintaining a Linux version for Cumulus due to the large matrix of Linux desktop environments where many of the advertised features might not work (media keys, notifications, task bar positioning with multi-screen setup etc.)

But please feel free to compile binaries for your own OS :)

**Comment by sclausen** [comment]
@gillesdemey you don't need to support it directly, but mentioning this ridiculous simple way to make a build for linux in the readme would be nice for every interested linux guy :wink:

**Comment by khaledvic** [comment]
well, we can help, but at least let's start by supporting debian based
dists, and let the community hadnle the reset .
@Sebastian (l)

**Comment by sebastian** [comment]
Hi @khaledvic, you got the wrong sebastian there, just in case you want to re-ping the right one.

**Comment by sclausen** [comment]
@sebastian Somehow I still got it :grin:

**Comment by sebastian** [comment]
@sclausen excellent :) Double Sebastian power in this instance. Ok, bye bye, signing out here.

**Pull request closed without merging**
